In [1]:
import numpy as np
# fixed type
# applications -> matlab, matplotlib, pandas, ML
print(np.__version__)

1.21.5


In [3]:
nums = np.array([1, 2, 3])
nums = np.array([1, 2, 3], 'int64')

print(nums)

print(nums.shape)
print(nums.dtype)
print(nums.ndim)
print(nums.size)
print(nums.itemsize)
print('sums', np.sum(nums))
print(nums[0], nums[1], nums[2])
print(nums[-1], nums[-2], nums[-3])

[1 2 3]
(3,)
int64
1
3
8
sums 6
1 2 3
3 2 1


In [80]:
nums = np.array([
    [1, 2, 3],
    [4, 5, 6]
], 'int64')
print(nums)

print(nums.shape)
print(nums.dtype)
print(nums.ndim)
print(nums.size)
print(nums.itemsize)
print(nums[0], nums[1])
print(nums[0][0], nums[0][1], nums[0][2])
print(nums[0][-1], nums[0][-2], nums[0][-3])
# use [,] instead of [][]
print(nums[0,0], nums[0,1], nums[0,2])
print(nums[1][0], nums[1][1], nums[1][2])
print(nums[-1][-1], nums[-1][-2], nums[-1][-3])

print('sums', np.sum(nums))

[[1 2 3]
 [4 5 6]]
(2, 3)
int64
2
6
8
[1 2 3] [4 5 6]
1 2 3
3 2 1
1 2 3
4 5 6
6 5 4
sums 21


In [28]:
nums = np.array([
    [
        [1, 2, 3],
        [11, 12, 13],
    ],
    [
        [4, 5, 6],
        [21, 22, 23],
    ],
    [
        [7, 8, 9],
        [31, 32, 33],
    ]
])
print(nums)

print(nums.shape)
print(nums.dtype)
print(nums.ndim)
print(nums.size)
print(nums.itemsize)
print(nums[0][0][0], nums[0][0][1], nums[0][0][2])
print(nums[0][1][0], nums[0][1][1], nums[0][1][2])
print(nums[1][0][0], nums[1][0][1], nums[1][0][2])

[[[ 1  2  3]
  [11 12 13]]

 [[ 4  5  6]
  [21 22 23]]

 [[ 7  8  9]
  [31 32 33]]]
(3, 2, 3)
int32
3
18
4
1 2 3
11 12 13
4 5 6


In [163]:
# Zeros matrix
nums = np.zeros((5, 3), 'int64')
print(nums)

# ones matrix
nums = np.ones((2, 3), 'int64')
print(nums)

# identity matrix
nums = np.identity(3, 'int64')
print(nums)

# full
nums = np.full((2, 3), 100)
print(nums)

# full_like
nums = np.array([1, 2, 3])
nums2 = np.full_like(nums, 10)
print(nums, nums2)

# sqrt
nums = np.array([1, 2, 3])
print(np.sqrt(nums))

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[100 100 100]
 [100 100 100]]
[1 2 3] [10 10 10]
[1.         1.41421356 1.73205081]


In [48]:
# convert to n dimension
arr = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
], ndmin=3)
print(arr)

[[[1 2 3 4]
  [5 6 7 8]]]


In [71]:
# matrix addition
nums1 = np.array([1, 2, 3])
print(5 + nums1)

# 2d
# matrix addition
nums1 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(5 + nums1)

# matrix subtraction
nums1 = np.array([1, 2, 3])
print(5 - nums1)

# 2d
# matrix subtraction
nums1 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(5 - nums1)

# matrix multiplication
nums1 = np.array([1, 2, 3])
print(5 * nums1)

# 2d
# matrix multiplication
nums1 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(nums1 * 5)

# matrix division
nums1 = np.array([1, 2, 3])
print(5 / nums1)

# 2d
# matrix division
nums1 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(nums1/5)

[6 7 8]
[[ 6  7  8]
 [ 9 10 11]]
[4 3 2]
[[ 4  3  2]
 [ 1  0 -1]]
[ 5 10 15]
[[ 5 10 15]
 [20 25 30]]
[5.         2.5        1.66666667]
[[0.2 0.4 0.6]
 [0.8 1.  1.2]]


In [77]:
# matrix multiplication
# 1d
nums1 = np.array([1, 2, 3])
nums2 = np.array([4, 5, 6])
print(np.multiply(nums1, nums2))

# 2d
nums1 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
nums2 = np.array([
    [5, 6, 7],
    [1, 2, 3]
])
print(np.multiply(nums1, nums2))

# 2d with diff shape
nums1 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
nums2 = np.array([
    [5, 6, 7],
    [1, 2, 3],
    [4, 5, 6]
])
# print(np.multiply(nums1, nums2))
print(np.dot(nums1, nums2))

[ 4 10 18]
[[ 5 12 21]
 [ 4 10 18]]
[[19 25 31]
 [49 64 79]]


In [171]:
# repeat array
nums = np.array([1, 2, 3])
nums2 = np.repeat(nums, 4)
print(nums, nums2)

# nums2 = np.repeat(nums, 4, axis=1) # error
nums = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
# nums2 = np.repeat(nums, 4, axis=0)
nums2 = np.repeat(nums, 4, axis=1)
print(nums2)

[1 2 3] [1 1 1 1 2 2 2 2 3 3 3 3]
[[1 1 1 1 2 2 2 2 3 3 3 3]
 [4 4 4 4 5 5 5 5 6 6 6 6]]


In [84]:
# list vs array
l1 = [1, 2, 3]
l2 = [4, 5, 6]

# dot product
dot = 0
for i in range(len(l1)):
    dot += l1[i] * l2[i]
    
print(dot)


arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(np.dot(arr1, arr2))

32
32


In [162]:
# list -> size, ref count, object type, object value
# non contiguous memory
# contiguous memory

# np.random.uniform(start,stop,(rows,columns))

# nums = np.random.uniform(low=2, high=10, size=(2,5))
# nums = np.random.randint(low=2, high=10, size=(2,5), dtype='int32')
# nums = np.random.rand(2, 3)
# print(nums)

[[0.91593729 0.35222828 0.51973416]
 [0.45207694 0.35318079 0.4285277 ]]


In [88]:
# speed test
from timeit import default_timer as t

a = np.random.random(1000)
b = np.random.random(1000)


l1 = list(a)
l2 = list(b)

def find_product():
    dot = 0
    for i in range(len(l1)):
        dot += l1[i] * l2[i]
    return dot

def find_dot():
    return np.dot(a, b)

start = t()
for i in range(1000):
    find_product()
end = t()
print(end - start)

start = t()
for i in range(1000):
    find_dot()
end = t()
print(end - start)

0.14095290000022942
0.0028615999999601627


In [141]:
# Slicing (row, col)
nums = np.array([1, 2, 3, 4, 5, 6, 7, 8])

# print(nums)
# print(nums[:])
# print(nums[2:5])
# print(nums[2:5:2])
# print(nums[-3:-1])
# print(nums[-6:-1: 2])


nums = np.array([
    [1, 2, 3, 4, 5, 6, 7, 8],
    [11, 12, 13, 14, 15, 16, 17, 18],
])

# print(nums)
# print(nums[:])
# print(nums[:1])
# print(nums[:2])
# print(nums[0:])
# print(nums[1:])

# print(nums[:1])
# print(nums[:2])
# print(nums[0:])
# print(nums[1:])

# rows and cols
# print(nums[0, :])
# print(nums[1, :])

# print(nums[0, 1:])
# print(nums[0, 1:4])
# print(nums[0, 1:4:2])

# print(nums[, 2:4]) # syntax error

# columns
# print(nums[:,2])
# print(nums[:,4])

# print(nums[0:, 4])
# print(nums[1:, 4])

# print(nums[0:1, 2:8:2])


# change values
# nums[1,3] = 10
# nums[:, 3:7] = 10
# print(nums)

[[ 1  2  3 10 10 10 10  8]
 [11 12 13 10 10 10 10 18]]


In [174]:
# copying array
arr = np.array([1, 2, 3])
copy = arr.copy()
print(arr, copy)
copy[0] = 10
print(arr, copy)

[1 2 3] [1 2 3]
[1 2 3] [10  2  3]


In [7]:
# cross product
v = np.array([4, 9, 12])
s = np.array([21, 32, 44])
r = np.cross(v, s)
print(r)

# reshaping arrays
nums = np.array([1, 2, 3, 4,  5, 6])
print(nums)

changed = nums.reshape(3,2)
print(nums)
print(changed)

changed = nums.reshape(1,6)
print(changed)

# changed = nums.reshape(2,4)
# print(changed)

nums = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

changed = nums.reshape(2,3)
print(changed)

[ 12  76 -61]
[1 2 3 4 5 6]
[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 3 4 5 6]]
[[1 2 3]
 [4 5 6]]


In [42]:
# vertical stacking
v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])

# print(np.vstack(v1))
# print(np.vstack([v1, v2, v1, v1, v1]))


v1 = np.full((2, 2), 10)
v2 = np.full((2, 2), 20)
# print(v1)
# print(v2)

# print(np.vstack([v1, v2, v2]))

[array([[1, 2, 3, 4],
       [4, 5, 6, 8]]),
 array([], shape=(0, 4), dtype=int32),
 array([], shape=(0, 4), dtype=int32)]


In [36]:
# horizontal stacking
h1 = np.array([1, 2, 3, 4])
h2 = np.array([5, 6, 7, 8])

# print(np.hstack(h1))
# print(np.hstack([h1, h2]))


h1 = np.full((2, 2), 10)
h2 = np.full((2, 2), 20)
# print(h1)
# print(h2)

# print(np.hstack([h1, h2, h2]))


[array([[1, 2],
       [4, 5]]),
 array([[3, 4],
       [6, 8]]),
 array([], shape=(2, 0), dtype=int32)]


In [66]:
# splitting

nums = np.array([
    [1, 2, 3, 4],
    [4, 5, 6, 8],
    [9, 10, 11, 12]
])

# print(np.split(nums, 3))
# print(np.split(nums, 3)[0])
# print(np.split(nums, 3)[1])
# print(np.split(nums, [1, 3]))
# print(np.split(nums, [1, 3])[0])
# print(np.split(nums, [1, 3])[1])


# hsplit
# print(np.hsplit(nums, 4))
# print(np.hsplit(nums, 4)[0])
# print(np.hsplit(nums, 4)[1])
# print(np.hsplit(nums, 2))
# print(np.hsplit(nums, 2)[0])
# print(np.hsplit(nums, 2)[1])
# print(np.hsplit(nums, [1, 3, 4]))
# print(np.hsplit(nums, [1, 3, 4])[0])
# print(np.hsplit(nums, [1, 3, 4])[1])
# print(np.hsplit(nums, [1, 3, 4])[2])

# vsplit
# print(np.vsplit(nums, 3))
# print(np.vsplit(nums, 3)[0])
# print(np.vsplit(nums, 3)[1])
# print(np.vsplit(nums, [1, 3]))
# print(np.vsplit(nums, [1, 3])[0])
# print(np.vsplit(nums, [1, 3])[1])

[array([[1, 2, 3, 4]]), array([[ 4,  5,  6,  8],
       [ 9, 10, 11, 12]]), array([], shape=(0, 4), dtype=int32)]
[[1 2 3 4]]
[[ 4  5  6  8]
 [ 9 10 11 12]]


In [17]:
# comparison operators
nums = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

# print(nums > 5)
# print(nums < 5)
# print(nums >= 5)
# print(nums <= 5)
# print(nums == 5)

less_than_5 = nums < 5
print(less_than_5)
print(nums[less_than_5])
print(nums[nums<5])

# where
nums2 = np.where(nums > 2)

[[ True  True  True]
 [ True False False]]
[1 2 3 4]
[1 2 3 4]


In [18]:
# index filtering
nums = np.array([1, 2, 3, 4, 5, 6, 7, 8])
index = np.array([1, 3, 5])
print(nums[index])

[2 4 6]


In [27]:
# arrange -> same as range
nums = np.arange(5, 10, 2)
print(nums)

# linspace
nums = np.linspace(1, 10, 10, dtype='int64')
print(nums)

[5 7 9]
[ 1  2  3  4  5  6  7  8  9 10]


In [3]:
# linear algebra
a = np.ones([2, 3])
b = np.full([3,3], 5)
print(np.matmul(a,b))

[[15. 15. 15.]
 [15. 15. 15.]]


In [11]:
# determinant -> ad - bc
nums = np.array([
    [1, 2],
    [4, 5]
], 'int64')
print(np.linalg.det(nums))

-2.9999999999999996


In [17]:
# inverse -> square matrix -> 1/det(mat) * adjoint(matrix)
# d -b
# -c a
nums = np.array([
    [1, 2],
    [4, 5]
])
print(np.linalg.inv(nums))

# transpose
nums = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(np.transpose(nums))

# sorting
nums = np.array([
    [1,4,2,3],
    [9,13,61,1],
    [43,24,88,22]
])    
print(np.sort(nums, axis=0))
print(np.sort(nums, axis=1))

[[-1.66666667  0.66666667]
 [ 1.33333333 -0.33333333]]
[[1 4]
 [2 5]
 [3 6]]
[[ 1  4  2  1]
 [ 9 13 61  3]
 [43 24 88 22]]
[[ 1  2  3  4]
 [ 1  9 13 61]
 [22 24 43 88]]


In [14]:
# Broadcasting

a = np.array([
    [1,2,3,4],
    [2,4,5,6],
    [10,20,39,3]
])  
b = np.array([2,4,6,8])  
print(a)  
print(b)    
print(a + b) 

[[ 1  2  3  4]
 [ 2  4  5  6]
 [10 20 39  3]]
[2 4 6 8]
[[ 3  6  9 12]
 [ 4  8 11 14]
 [12 24 45 11]]


In [28]:
# statistics
nums = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(np.mean(nums))
print(np.median(nums))
print(np.average(nums))
# std deviation = sqrt(mean(abs(x - x.mean())**2))
print(np.std(nums))
#  variance = mean(abs(x - x.mean())**2)
print(np.var(nums))

5.0
5.0
5.0
2.581988897471611
6.666666666666667


In [73]:
# loading file
values = np.genfromtxt('data.txt', delimiter=',')
print(np.sum(values))

2792.0
